export const messageText = {
  /*------------------ AUTH --------------*/
  INCORRECT_PASSWORD: "INCORRECT_PASSWORD",
  ACCOUNT_DOES_NOT_EXIST: "ACCOUNT_DOES_NOT_EXIST",
  ERROR_DATA_BASE: "ERROR_DATA_BASE",
  EMAIL_ALREADY_REGISTERED:
    "THE_EMAIL_IS_ALREADY_REGISTERED_AND_HAS_NOT_BEEN_VERIFIED ",
  INCORRECT_CODE: "INCORRECT_CODE",
  SUCCESSFULLY_VERFIFIED: "SUCCESSFULLY_VERFIFIED",
  EMAIL_WITH_CHANGE_PASS_SENT: "EMAIL_WITH_CHANGE_PASS_SENT",
  PASSWORD_IS_NOT_ACTIVED: "PASSWORD_ACTIVATION_IS_NOT_ACTIVATED",
  PASSWORD_CHANGED_SUCCESFULLY: "PASSWORD_CHANGED_SUCCESFULLY",
  /*------------------ INVENTORY --------------*/
  INVENTORY_CREATED_SUCCESSFULLY: "INVENTORY_CREATED_SUCCESSFULLY",
  USER_OR_INVENTORY_DOES_NOT_EXIST: "USER_OR_INVENTORY_DOES_NOT_EXIST",
  VALUE_EXCEEDS_TOTAL_DEBT: "VALUE_EXCEEDS_TOTAL_DEBT",
  THE_INVENTORY_DOES_NOT_EXIST: "THE_INVENTORY_DOES_NOT_EXIST",
  THE_ELIMINATED_INVENTORY: "THE_ELIMINATED_INVENTORY",
  INVENTORY_UPDATED_CORRECTLY: "INVENTORY_UPDATED_CORRECTLY",
};
